version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "vibeguardian-stack"
s3_prefix = "vibeguardian"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.build]
[default.build.parameters]
cached = true
parallel = true

